name: velox-scientiam-functions-CI

on:
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
        with:
            node-version: 10
        
        - name: install deps
            run: yarn --frozen-lockfile --ci
        - name: build
            run: yarn build